name: mc866-pf

channels:
  - intel
  - conda-forge

dependencies:
  - pip
  - python=3.8
  - cudnn
  - cudatoolkit=11.0
  - numpy=1.19
  - jupyterlab
  - ipython
  - pathlib

  - pip:
    - openvino
    - openvino-dev[tensorflow2,caffe,pytorch,onnx]
